PORT_GRPC=3000
PORT_REST=4000
PRODUCTION=false

CONSUL_HOST=localhost:8500
CONSUL_TOKEN=""
CONSUL_KEY_FOLDER=auth
CONSUL_KEY_VERSION=v1.0.0
CONSUL_KEY_FILE=config.yaml

TRACER_URL=http://localhost:14268/api/traces
TRACER_NAME=auth

VAULT_MOUNT_PATH=authentication
VAULT_PUBLIC_CERT_PATH=crt/public
VAULT_PRIVATE_CERT_PATH=crt/private
VAULT_REDIS_CREDS_PATH=redis
VAULT_TOKEN=auth-token
VAULT_HOST=http://localhost:8200

ENV = PORT_GRPC=$(PORT_GRPC) PORT_REST=$(PORT_REST) PRODUCTION=$(PRODUCTION) CONSUL_HOST=$(CONSUL_HOST) CONSUL_TOKEN=$(CONSUL_TOKEN) CONSUL_KEY_FOLDER=$(CONSUL_KEY_FOLDER) CONSUL_KEY_VERSION=$(CONSUL_KEY_VERSION) CONSUL_KEY_FILE=$(CONSUL_KEY_FILE) TRACER_URL=$(TRACER_URL) TRACER_NAME=$(TRACER_NAME) VAULT_MOUNT_PATH=$(VAULT_MOUNT_PATH) VAULT_PUBLIC_CERT_PATH=$(VAULT_PUBLIC_CERT_PATH) VAULT_PRIVATE_CERT_PATH=$(VAULT_PRIVATE_CERT_PATH) VAULT_REDIS_CREDS_PATH=$(VAULT_REDIS_CREDS_PATH) VAULT_TOKEN=$(VAULT_TOKEN) VAULT_HOST=$(VAULT_HOST)

run:
	$(ENV) go run .

proto:
	protoc --go_out=./auth --go_opt=paths=source_relative \
    --go-grpc_out=./auth --go-grpc_opt=paths=source_relative \
    scheme.proto